version: "3"

services:
    db:
        image: postgres:12
        container_name: biblioteca_db
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data

    web_app:
        build: .
        image: biblioteca:1.0.0
        container_name: biblioteca_app
        env_file:
            - .env
        volumes:
            - static:/code/static
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db

    nginx:
        image: nginx:1.19.0-alpine
        container_name: biblioteca_nginx
        ports:
            - 80:80
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - static:/code/static
        depends_on:
            - web_app

volumes:
    .:
    postgres_data:
    static:
