version: "3"

services:
    web:
        build: .
        image: biblioteca:v1.0.0
        container_name: biblioteca
        env_file:
            - .env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
volumes:
    .:
