# Generated by Django 3.2.9 on 2022-01-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn" target="_blank">Numero ISBN</a>', max_length=13, verbose_name='ISBN'),
        ),
    ]
